version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # ローカルホストの3000番ポートにマッピング
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001" # ローカルホストの3001番ポートにマッピング
    volumes:
      - ./backend:/app
